<?php

namespace Proxies\__CG__\Bs\FrontOfficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \Bs\FrontOfficeBundle\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('path' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->path);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'idevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'nomevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'lieuevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'dateevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'organisateur', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'nbrevisiteur', 'path', 'file', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'filenameForRemove');
        }

        return array('__isInitialized__', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'idevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'nomevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'lieuevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'dateevenement', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'organisateur', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'nbrevisiteur', 'file', '' . "\0" . 'Bs\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'filenameForRemove');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->path);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function storeFilenameForRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'storeFilenameForRemove', array());

        return parent::storeFilenameForRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdevenement()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdevenement();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdevenement', array());

        return parent::getIdevenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomevenement($nomevenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomevenement', array($nomevenement));

        return parent::setNomevenement($nomevenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomevenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomevenement', array());

        return parent::getNomevenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuevenement($lieuevenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuevenement', array($lieuevenement));

        return parent::setLieuevenement($lieuevenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuevenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuevenement', array());

        return parent::getLieuevenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateevenement($dateevenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateevenement', array($dateevenement));

        return parent::setDateevenement($dateevenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateevenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateevenement', array());

        return parent::getDateevenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisateur($organisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisateur', array($organisateur));

        return parent::setOrganisateur($organisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisateur', array());

        return parent::getOrganisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrevisiteur($nbrevisiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrevisiteur', array($nbrevisiteur));

        return parent::setNbrevisiteur($nbrevisiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrevisiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrevisiteur', array());

        return parent::getNbrevisiteur();
    }

}
